# Generated by Django 2.1.9 on 2019-08-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
