# Generated by Django 2.1.9 on 2019-08-19 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mykey',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
